language: node_js
os: linux
dist: xenial
node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: 14
      deploy:
        provider: npm
        email: rogier+npm@konfirm.eu
        on:
          branch: master
          tags: true
        api_key:
